config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :staff
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get 'dashboard' => 'dashboard#index', as: :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/staff.rb
class Staff < ApplicationRecord
  include AASM
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :timeoutable, :trackable, :recoverable, :validatable, :registerable

  enum role: %i[admin hq-agent student agent]

  # Validations
  # validates :phone_number, uniqueness: true, presence: true, phone: {
  #   possible: true,
  #   allow_blank: true,
  #   types: [:mobile],
  #   countries: [:in]
  # }

  validates :email, uniqueness: true
  before_validation :setup_and_format_phone_number

  aasm column: :status do
    state :active, initial: true
    state :inactive

    event :activate do
      transitions from: :inactive, to: :active
    end

    event :deactivate do
      transitions from: :active, to: :inactive
    end
  end
  
  before_save do
    if self.new_record?
      self.role ||= :admin
    end
  end



  def setup_and_format_phone_number
    unless phone_number.blank?
      phone = Phonelib.parse(phone_number, "IN")
      unless phone.invalid?
        self.phone_number = phone.e164
      end
    end
  end
  
  def setup_defaults
    self.phone_number = Phonelib.parse(phone_number, "IN").e164
  end
end

app/models/student.rb
class Student < ApplicationRecord
  validates :email, uniqueness: true
  validates :phone_number, uniqueness: true
  validates :registered_id, uniqueness: true

  before_validation :generate_registered_id

  def full_name
    first_name + " " + last_name
  end

  def generate_registered_id
    # generate upto 10 digit length numbers and convert to a string with base 10
    # then pad 0s if the length of the number is less than 10
    if registered_id.blank?
      i = 0
      loop do
        random_number = SecureRandom.random_number(10**10).to_s(10).rjust(10, "0").upcase
        # Prefix will provide extra grouping in future
        # Stock Location + Store can be a prefix combination
        # We could also archive a complete group if necessary of orders and rotate the prefix to next alphabet
        num = "A#{random_number}"
        self.registered_id = num
        i += 1
        break if Student.find_by(registered_id: num).blank? || i >= 10
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  protected

  def current_user
    current_staff
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_staff!

  def index
    @staff = current_user
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_url, notice: "Student was successfully created." }
        format.json { head :no_content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :dob, :nationality, :email, :registered_id, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/dashboard/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container-fluid ml-0">
      <h1>Welcome <%= @staff.name %>!</h1>
    </div>
  </div>
<% end %>

<div class="container-fluid">
  <div class="row">

  <!-- Icon Cards-->
    <div class="col-lg-4 col-md-4 col-sm-6 col-12 mb-2 mt-4">
        <div class="inforide">
          <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-4 col-4 rideone">
                <img src="">
            </div>
            <div class="col-lg-9 col-md-8 col-sm-8 col-8 fontsty">
                <h4>Data</h4>
                <h2>100</h2>
            </div>
          </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-6 col-12 mb-2 mt-4">
        <div class="inforide">
          <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-4 col-4 ridetwo">
                <img src="">
            </div>
            <div class="col-lg-9 col-md-8 col-sm-8 col-8 fontsty">
                <h4>Data</h4>
                <h2>120</h2>
            </div>
          </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-4 col-sm-6 col-12 mb-2 mt-4">
        <div class="inforide">
          <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-4 col-4 ridethree">
                <img src="">
            </div>
            <div class="col-lg-9 col-md-8 col-sm-8 col-8 fontsty">
                <h4>Data</h4>
                <h2>50</h2>
            </div>
          </div>
        </div>
    </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% unless flash.blank? %>
  <div class="alert alert-primary" role="alert">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
  </div>
  <% end %>
    <nav class="navbar navbar-light bg-dark fixed-top ">
      <div><a class="navbar-brand" href="/"><span class="text-white">Admin</span></a></div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav nav-pills nav-fill">
        <% if staff_signed_in? %>
          <li class="nav-item"><%=link_to "Dashboard", dashboard_path, class:"nav-link text-light", id:"dashboard-tab"%></li>
        <% end %>
      </ul>
      <ul class="nav justify-content-end"">
        <% if staff_signed_in? %>
          <li class="nav-item"><%= link_to current_staff.email, edit_staff_registration_path,class:"nav-link text-light" %></li>
          <li class="nav-item"><%= link_to 'Log out', destroy_staff_session_path, method: :delete,class:"nav-link text-light" %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Log In', new_staff_session_path ,class:"nav-link text-light"%></li>
        <% end %>
      </ul>
  </nav>
    
    
    <div class="body-pad">  
    <%= yield :top_content %>
    <div class="container">
      <h1><%= yield :header %></h1>

    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for(@student) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs form-group">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :dob, start_year: Time.now.year-50, end_year: Time.now.year-15, order: %i(day month year) %>
    <%= f.input :nationality %>
    <%= f.input :email %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-xs btn-success" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<div class="container pl-0 ml-0">
  <% @students.each do |student| %>
    <div class="row row-cols-3 m-2 ">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= student.full_name %></h5>
          <h7 class="card-subtitle text-muted">Date of Birth: <%= student.dob.strftime("%d %b %Y") %></h7><br>
          <h7 class="card-subtitle text-muted">Email: <%= student.email %></h7><br>
          <h7 class="card-subtitle text-muted">Nationality: <%= student.nationality %></h7><br>
          <p class="card-text"></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"></li>
          <li class="list-group-item">Registered ID: <%= student.registered_id %></li>
          <li class="list-group-item">Contact: <%= student.phone_number %></li>
        </ul>
        <div class="card-body">
          <%= link_to 'Edit', edit_student_path(student), class: "card-link" %>
          <%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link" %>
          <%= link_to 'Show', student, class: "card-link" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Student', new_student_path, class: "btn btn-xs btn-success" %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @student.dob %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @student.nationality %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Registered:</strong>
  <%= @student.registered_id %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @student.phone_number %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>